version: 0.2

env:
  variables:
    key: "S3_BUCKET"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands: #https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/
      - npm install -g newman
      - yum install -y jq

  pre_build:
    commands:
      - echo prebuild started on `date` from dir `pwd`
      - aws s3 cp "s3://${S3_BUCKET}/postman-env-files/PetStoreAPIEnvironment.postman_environment.json" ./02postman/
      - aws s3 cp "s3://${S3_BUCKET}/postman-env-files/PetStoreAPI.postman_collection.json" ./02postman/
      - cd ./02postman
      - ./update-postman-env-file.sh
      - cd ..
      - aws s3 cp "s3://${S3_BUCKET}/postman-env-files/PetStoreAPIEnvironment.postman_environment.json" ./02_1postman/
      - aws s3 cp "s3://${S3_BUCKET}/postman-env-files/PetStoreAPI.postman_collection.json" ./02_1postman/
      - cp ./02postman/update-postman-env-file.sh ./02_1postman/
      - cd ./02_1postman/
      - ls -lrt
      - ./update-postman-env-file.sh


  build:
    commands:
      - echo Build started on `date` from dir `pwd`
      - cd ..
      - pwd
      - mkdir newman/02postman
      - cd ./02postman
      - newman run PetStoreAPI.postman_collection.json --environment PetStoreAPIEnvironment.postman_environment.json -r junit --reporter-junit-export ../newman/02postman
      - cd ../ 
      - newman/02_1postman
      - cd ../02_1postman
      - echo Build started on `date` from dir `pwd`
      - newman run PetStoreAPI.postman_collection.json --environment PetStoreAPIEnvironment.postman_environment.json -r junit
      - cd .. 
      - cp ./02postman/create-report-groups.sh .
      - chmod 764 create-report-groups.sh
      - ./create-report-groups.sh

reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'newman/02_postman' # Location of the reports
  PostDeploymentReport:
    files: #Store all of the files
      - '**/*'
    base-directory: 'newman/02_1postman' # Location of the reports
